version: '3'
services:
  meet_the_team:
    build: .
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
      PRODUCTION: 'true'
      RANDOM_USER_API_URL: https://randomuser.me/api
      RANDOM_USER_DOMAIN_URL: randomuser.me